'physical':
  - kberat-synnada
  - norhan-synnada

'models':
  - kberat-synnada
  - norhan-synnada

'logical':
  - kberat-synnada
  - norhan-synnada

'backend':
  - kberat-synnada
  - norhan-synnada

'tests':
  - kberat-synnada
  - norhan-synnada

'examples':
  - kberat-synnada
  - norhan-synnada

'codegen':
  - kberat-synnada
  - norhan-synnada

'constraints':
  - kberat-synnada
  - norhan-synnada

'benchmarks':
  - kberat-synnada
  - norhan-synnada

'utils':
  - kberat-synnada
  - norhan-synnada

'framework-utils':
  - kberat-synnada
  - norhan-synnada

'common':
  - kberat-synnada
  - norhan-synnada

